### ISSUE TITLE
Upgrade Stack to Latest Node.js

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/ac#10]
This app is running on an _ancient_ version of Node.js  https://dashboard.heroku.com/apps/wordsy/settings
![image](https://user-images.githubusercontent.com/194400/111007811-9b0bd680-8387-11eb-85b2-e9cd9ee97ca4.png)

It was last deployed July 2014 ... 
![image](https://user-images.githubusercontent.com/194400/111007946-e7571680-8387-11eb-8b68-b252b889d2dc.png)

# Todo

+ [ ] Update all `devDependencies`
+ [ ] Update any code if necessary
+ [ ] Update tests if necessary
+ [ ] Update badges to be consistent
+ [ ] Deploy new version
